// src/components/ServiceCard.tsx
import { Card } from "@/components/ui/card";
import { LucideIcon } from "lucide-react";

interface ServiceCardProps {
  icon: LucideIcon;
  title: string;
  description: string;
  features: string[];
}

export const ServiceCard = ({ icon: Icon, title, description, features }: ServiceCardProps) => {
  return (
    <Card className="group relative overflow-hidden p-6 bg-card-gradient border border-border/50 transform-gpu will-change-transform transition-transform duration-300 ease-smooth hover:-translate-y-1.5 hover:scale-[1.02] hover:shadow-card">
      <div className="absolute inset-0 opacity-0 transition-opacity duration-300 ease-smooth group-hover:opacity-100 bg-gradient-to-br from-primary/10 via-transparent to-accent/10" />
      <div className="relative flex flex-col items-center text-center space-y-4">
        <div className="p-4 rounded-full bg-primary-gradient shadow-elegant transform-gpu will-change-transform transition-transform duration-300 ease-smooth group-hover:shadow-glow group-hover:-translate-y-1">
          <Icon className="h-8 w-8 text-primary-foreground transform-gpu will-change-transform transition-transform duration-300 ease-smooth group-hover:scale-110" />
        </div>

        <h3 className="text-xl font-bold text-foreground transition-colors duration-500 ease-smooth group-hover:text-primary">
          {title}
        </h3>

        <p className="text-muted-foreground leading-relaxed transition-colors duration-500 ease-smooth group-hover:text-foreground/90">
          {description}
        </p>

        <ul className="space-y-2 w-full">
          {features.map((feature, index) => (
            <li
              key={index}
              className="flex items-center justify-center space-x-2 text-sm text-muted-foreground transition-colors duration-500 ease-smooth group-hover:text-foreground"
            >
              <div className="w-1.5 h-1.5 rounded-full bg-accent transform-gpu will-change-transform transition-transform duration-300 ease-smooth group-hover:scale-125" />
              <span>{feature}</span>
            </li>
          ))}
        </ul>

      </div>
    </Card>
  );
};

// components/ServiceCard.vue
<template>
  <div
    ref="cardRef"
    class="glass-panel neon-border rounded-3xl p-6 transition-all duration-500 hover:scale-[1.02] hover:shadow-xl"
    :class="[inView ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8']"
    :style="{ transitionDelay: `${delay}ms` }"
  >
    <!-- Icon -->
    <div class="mb-4 inline-flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-primary/20 to-secondary/20">
      <component :is="icon" class="h-7 w-7 text-primary" />
    </div>

    <!-- Title -->
    <h3 class="mb-3 text-xl font-semibold text-foreground">
      {{ title }}
    </h3>

    <!-- Description -->
    <p class="mb-4 text-sm text-muted-foreground leading-relaxed">
      {{ description }}
    </p>

    <!-- Features List -->
    <ul v-if="features.length > 0" class="space-y-2">
      <li
        v-for="(feature, index) in features.slice(0, 3)"
        :key="index"
        class="flex items-center gap-2 text-sm text-muted-foreground"
      >
        <Check class="h-4 w-4 text-primary flex-shrink-0" />
        <span>{{ feature }}</span>
      </li>
    </ul>

    <!-- CTA -->
    <NuxtLink
      to="/order"
      class="mt-6 inline-flex items-center gap-2 text-sm font-medium text-primary hover:text-primary/80 transition-colors cursor-interactive"
    >
      {{ $t('services.orderNow', 'Pesan Sekarang') }}
      <ArrowRight class="h-4 w-4" />
    </NuxtLink>
  </div>
</template>

<script setup lang="ts">
import { Check, ArrowRight } from 'lucide-vue-next'
import type { Component } from 'vue'

interface Props {
  icon: Component
  title: string
  description: string
  features?: string[]
  delay?: number
}

const props = withDefaults(defineProps<Props>(), {
  features: () => [],
  delay: 0
})

const cardRef = ref<HTMLElement | null>(null)
const inView = ref(false)

onMounted(() => {
  if (!cardRef.value) return
  
  const observer = new IntersectionObserver(
    ([entry]) => {
      if (entry.isIntersecting) {
        inView.value = true
        observer.disconnect()
      }
    },
    { threshold: 0.1 }
  )
  
  observer.observe(cardRef.value)
  
  onUnmounted(() => {
    observer.disconnect()
  })
})
</script>
