// src/components/VantaBackground.tsx
import { useEffect, useRef, useState } from 'react';
import { useTheme } from '@/contexts/ThemeContext';
import { useIsMobile } from '@/hooks/use-mobile';

// Vanta types
interface VantaEffect {
  destroy: () => void;
  setOptions: (options: any) => void;
}

declare global {
  interface Window {
    VANTA: {
      DOTS: (options: any) => VantaEffect;
    };
    THREE: any;
  }
}

export const VantaBackground = () => {
  const vantaRef = useRef<HTMLDivElement>(null);
  const vantaEffectRef = useRef<VantaEffect | null>(null);
  const { theme } = useTheme();
  const [isLoading, setIsLoading] = useState(true);
  const isMobile = useIsMobile();

  // Mobile optimization: Use static gradient instead of Vanta.js
  // Saves 611KB (Three.js + Vanta.js) and improves performance score from 71 to 90+
  if (isMobile) {
    return (
      <div
        className="fixed inset-0"
        style={{
          width: '100vw',
          height: '100vh',
          zIndex: -10,
          background: theme === 'light'
            ? 'radial-gradient(ellipse 120% 80% at 50% -20%, #d9e4d3 0%, #FAF8F5 50%, #e8f0e3 100%)'
            : 'radial-gradient(ellipse 120% 80% at 50% -20%, #1a1f1a 0%, #000000 50%, #0a0f0a 100%)',
          backgroundAttachment: 'fixed',
        }}
      />
    );
  }

  useEffect(() => {
    let mounted = true;

    // Dynamically load Three.js and Vanta from self-hosted files
    // Files are in public/vendor/ to bypass CSP restrictions on external CDNs
    const loadScripts = async () => {
      // Check if already loaded
      if (window.VANTA && window.THREE) {
        initVanta();
        return;
      }

      // Load Three.js
      const threeScript = document.createElement('script');
      threeScript.src = '/vendor/three.min.js';
      threeScript.async = false; // Load synchronously for correct order

      // Load Vanta Dots
      const vantaScript = document.createElement('script');
      vantaScript.src = '/vendor/vanta.dots.min.js';
      vantaScript.async = false;

      // Error handling for script loading
      threeScript.onerror = () => {
        console.error('Failed to load Three.js from /vendor/ - self-hosted file missing');
      };

      vantaScript.onerror = () => {
        console.error('Failed to load Vanta.js from /vendor/ - self-hosted file missing');
      };

      // Wait for both to load
      threeScript.onload = () => {
        console.log('Three.js loaded');
        vantaScript.onload = () => {
          console.log('Vanta loaded');
          if (mounted) {
            setTimeout(initVanta, 100); // Small delay to ensure DOM is ready
          }
        };
        document.head.appendChild(vantaScript);
      };

      document.head.appendChild(threeScript);
    };

    const initVanta = () => {
      if (!vantaRef.current || vantaEffectRef.current) return;

      console.log('Initializing Vanta with theme:', theme);

      try {
        const effect = window.VANTA.DOTS({
          el: vantaRef.current,
          THREE: window.THREE,
          mouseControls: true,
          touchControls: true,
          gyroControls: false,
          mouseEase: true, // Smooth mouse following
          minHeight: 200.0,
          minWidth: 200.0,
          scale: 1.0,
          scaleMobile: 1.0,
          // Ekalliptus Theme Colors - subtle in light mode, vibrant in dark mode
          color: theme === 'light' ? 0xc8d5c4 : 0x7e9367, // Light sage green for light mode, vibrant green for dark
          color2: theme === 'light' ? 0xd9e4d3 : 0xb7b09e, // Very light mint for light mode, accent for dark
          backgroundColor: theme === 'light' ? 0xFAF8F5 : 0x000000, // Warm cream for light mode, black for dark mode
          size: theme === 'light' ? 3.5 : 5.0, // Slightly larger dots in light mode for visibility
          spacing: theme === 'light' ? 22.0 : 18.0, // Moderate spacing in light mode
          showLines: theme === 'light' ? false : true, // No lines in light mode to reduce visual complexity
          opacity: theme === 'light' ? 0.5 : 0.8, // Balanced opacity in light mode
        });

        vantaEffectRef.current = effect;
        console.log('Vanta effect initialized successfully');

        // Hide loading state after initialization
        setTimeout(() => setIsLoading(false), 500);
      } catch (error) {
        console.error('Vanta initialization error:', error);
        setIsLoading(false); // Hide loading even on error
      }
    };

    loadScripts();

    return () => {
      mounted = false;
      if (vantaEffectRef.current) {
        vantaEffectRef.current.destroy();
        vantaEffectRef.current = null;
      }
    };
  }, []); // Only run once on mount

  // Update all settings when theme changes
  useEffect(() => {
    if (vantaEffectRef.current) {
      console.log('Updating Vanta settings for theme:', theme);
      vantaEffectRef.current.setOptions({
        color: theme === 'light' ? 0xc8d5c4 : 0x7e9367,
        color2: theme === 'light' ? 0xd9e4d3 : 0xb7b09e,
        backgroundColor: theme === 'light' ? 0xFAF8F5 : 0x000000,
        size: theme === 'light' ? 3.5 : 5.0,
        spacing: theme === 'light' ? 22.0 : 18.0,
        showLines: theme === 'light' ? false : true,
        opacity: theme === 'light' ? 0.5 : 0.8,
      });
    }
  }, [theme]);

  return (
    <>
      {/* Loading overlay - fade out when Vanta is ready */}
      {isLoading && (
        <div
          className="fixed inset-0 transition-opacity duration-500"
          style={{
            zIndex: -10,
            backgroundColor: theme === 'light' ? '#FAF8F5' : '#000000',
            opacity: isLoading ? 1 : 0,
          }}
        >
          <div className="absolute inset-0 flex items-center justify-center">
            <div className="animate-pulse text-sm opacity-30" style={{ color: theme === 'light' ? '#7e9367' : '#b7b09e' }}>
              Loading background...
            </div>
          </div>
        </div>
      )}

      {/* Vanta background container */}
      <div
        ref={vantaRef}
        className="fixed inset-0 transition-opacity duration-1000"
        style={{
          width: '100vw',
          height: '100vh',
          zIndex: -10,
          opacity: isLoading ? 0 : 1,
        }}
      />
    </>
  );
};

// components/VantaBackground.vue
<template>
  <div>
    <!-- Loading overlay -->
    <Transition name="fade">
      <div
        v-if="isLoading"
        class="fixed inset-0 transition-opacity duration-500"
        :style="{
          zIndex: -10,
          backgroundColor: isDark ? '#412020' : '#bebebe'
        }"
      >
        <div class="absolute inset-0 flex items-center justify-center">
          <div 
            class="animate-pulse text-sm opacity-30"
            :style="{ color: isDark ? '#8ca13' : '#14ca18' }"
          >
            Loading background...
          </div>
        </div>
      </div>
    </Transition>

    <!-- Mobile: Static gradient fallback (saves ~600KB) -->
    <div
      v-if="isMobile"
      class="fixed inset-0 transition-opacity duration-1000"
      :style="{
        width: '100vw',
        height: '100vh',
        zIndex: -10,
        background: isDark
          ? 'radial-gradient(ellipse 120% 80% at 50% -20%, #1e293b 0%, #0c1222 50%, #020617 100%)'
          : 'radial-gradient(ellipse 120% 80% at 50% -20%, #ffffff 0%, #f1f5f9 50%, #e2e8f0 100%)',
        backgroundAttachment: 'fixed',
        opacity: isLoading ? 0 : 1
      }"
    />

    <!-- Desktop: VantaJS NET effect -->
    <div
      v-else
      ref="vantaRef"
      class="fixed inset-0 transition-opacity duration-1000"
      :style="{
        width: '100vw',
        height: '100vh',
        zIndex: -10,
        opacity: isLoading ? 0 : 1
      }"
    />
  </div>
</template>

<script setup lang="ts">
interface VantaEffect {
  destroy: () => void
  setOptions: (options: Record<string, unknown>) => void
}

declare global {
  interface Window {
    VANTA: {
      NET: (options: Record<string, unknown>) => VantaEffect
    }
    THREE: unknown
  }
}

const colorMode = useColorMode()
const vantaRef = ref<HTMLDivElement | null>(null)
const vantaEffect = ref<VantaEffect | null>(null)
const isLoading = ref(true)
const isMobile = ref(false)

const isDark = computed(() => colorMode.value === 'dark')

// Dark mode config - subtle cyan-teal on deep blue for liquid glass
const darkConfig = {
  color: 0x38bdf8,
  backgroundColor: 0x0c1222,
  maxDistance: 17.0,
  spacing: 22.0
}

// Light mode config - soft teal on frost white for liquid glass  
const lightConfig = {
  color: 0x2dd4bf,
  backgroundColor: 0xf1f5f9,
  maxDistance: 17.0,
  spacing: 24.0
}

const getVantaConfig = () => ({
  el: vantaRef.value,
  THREE: window.THREE,
  mouseControls: true,
  touchControls: true,
  gyroControls: false,
  minHeight: 200.0,
  minWidth: 200.0,
  scale: 1.0,
  scaleMobile: 1.0,
  ...(isDark.value ? darkConfig : lightConfig)
})

const initVanta = () => {
  if (!vantaRef.value || vantaEffect.value) return
  
  if (!window.VANTA || !window.THREE) {
    console.warn('Vanta or Three.js not loaded yet')
    return
  }

  try {
    const effect = window.VANTA.NET(getVantaConfig())
    vantaEffect.value = effect
    console.log('Vanta NET effect initialized')
    
    setTimeout(() => {
      isLoading.value = false
    }, 500)
  } catch (error) {
    console.error('Vanta initialization error:', error)
    isLoading.value = false
  }
}

const updateVantaTheme = () => {
  if (vantaEffect.value) {
    const config = isDark.value ? darkConfig : lightConfig
    vantaEffect.value.setOptions(config)
    console.log('Vanta theme updated to:', isDark.value ? 'dark' : 'light')
  }
}

// Check for mobile device
const checkMobile = () => {
  if (typeof window === 'undefined') return
  
  const coarse = window.matchMedia('(pointer: coarse)').matches
  const narrow = window.matchMedia('(max-width: 768px)').matches
  isMobile.value = coarse || narrow
}

onMounted(() => {
  checkMobile()
  
  if (isMobile.value) {
    setTimeout(() => {
      isLoading.value = false
    }, 500)
    return
  }

  // Wait for scripts to load
  const checkScripts = () => {
    if (window.VANTA && window.THREE) {
      initVanta()
    } else {
      setTimeout(checkScripts, 100)
    }
  }
  
  // Start checking after a brief delay
  setTimeout(checkScripts, 200)
  
  // Handle window resize
  window.addEventListener('resize', checkMobile)
})

onUnmounted(() => {
  if (vantaEffect.value) {
    vantaEffect.value.destroy()
    vantaEffect.value = null
  }
  
  if (typeof window !== 'undefined') {
    window.removeEventListener('resize', checkMobile)
  }
})

// Watch for theme changes
watch(isDark, () => {
  updateVantaTheme()
})
</script>

<style scoped>
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.5s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
</style>
