// components/CustomCursor.vue
<template>
  <div
    v-if="!isTouch"
    ref="cursorRef"
    class="pointer-events-none fixed z-[9999] mix-blend-difference"
    :style="cursorStyle"
  >
    <!-- Outer ring -->
    <div
      class="absolute rounded-full border-2 border-white transition-all duration-200 ease-out"
      :class="[
        isHovering ? 'w-12 h-12 -translate-x-1/2 -translate-y-1/2 opacity-50' : 'w-8 h-8 -translate-x-1/2 -translate-y-1/2 opacity-80'
      ]"
    />
    
    <!-- Inner dot -->
    <div
      class="absolute w-1.5 h-1.5 -translate-x-1/2 -translate-y-1/2 rounded-full bg-white transition-all duration-100"
      :class="[isHovering ? 'scale-0' : 'scale-100']"
    />
  </div>
</template>

<script setup lang="ts">
const cursorRef = ref<HTMLDivElement | null>(null)
const isTouch = ref(true)
const isHovering = ref(false)
const position = ref({ x: 0, y: 0 })

const cursorStyle = computed(() => ({
  left: `${position.value.x}px`,
  top: `${position.value.y}px`,
  transform: 'translate(-50%, -50%)'
}))

let rafId: number | null = null

const handleMouseMove = (e: MouseEvent) => {
  if (rafId) return
  rafId = requestAnimationFrame(() => {
    position.value = { x: e.clientX, y: e.clientY }
    rafId = null
  })
}

const handleMouseOver = (e: MouseEvent) => {
  const target = e.target as HTMLElement
  const interactive = target.closest('.cursor-interactive, a, button, [role="button"], input, textarea, select')
  isHovering.value = !!interactive
}

const styleElement = ref<HTMLStyleElement | null>(null)

onMounted(() => {
  if (typeof window === 'undefined') return
  
  const coarse = window.matchMedia('(pointer: coarse)').matches
  const narrow = window.matchMedia('(max-width: 768px)').matches
  isTouch.value = coarse || narrow
  
  if (!isTouch.value) {
    document.addEventListener('mousemove', handleMouseMove)
    document.addEventListener('mouseover', handleMouseOver)
    
    document.body.style.cursor = 'none'
    
    const style = document.createElement('style')
    style.textContent = `
      a, button, [role="button"], input, textarea, select, .cursor-interactive {
        cursor: none !important;
      }
    `
    document.head.appendChild(style)
    styleElement.value = style
  }
})

onUnmounted(() => {
  if (typeof window !== 'undefined') {
    if (rafId) {
      cancelAnimationFrame(rafId)
      rafId = null
    }
    if (!isTouch.value) {
      document.removeEventListener('mousemove', handleMouseMove)
      document.removeEventListener('mouseover', handleMouseOver)
      document.body.style.cursor = ''
      styleElement.value?.remove()
    }
  }
})
</script>

// src/components/CustomCursor.tsx
import { useEffect, useRef, useState } from "react";

export const CustomCursor = () => {
  const cursorRef = useRef<HTMLDivElement>(null);
  const followerRef = useRef<HTMLDivElement>(null);
  const [shouldRender, setShouldRender] = useState(true);

  useEffect(() => {
    if (typeof window === "undefined") return;
    const media = window.matchMedia("(pointer: coarse)");
    setShouldRender(!media.matches);

    const handleChange = (event: MediaQueryListEvent) => {
      setShouldRender(!event.matches);
    };

    media.addEventListener("change", handleChange);
    return () => media.removeEventListener("change", handleChange);
  }, []);

  useEffect(() => {
    if (typeof document === "undefined") return;
    const className = "custom-cursor-enabled";
    if (shouldRender) {
      document.body.classList.add(className);
    } else {
      document.body.classList.remove(className);
    }
    return () => {
      document.body.classList.remove(className);
    };
  }, [shouldRender]);

  useEffect(() => {
    if (!shouldRender) return;

    const cursor = cursorRef.current;
    const follower = followerRef.current;
    if (!cursor || !follower) return;

    let rafId: number | null = null;

    const setOpacity = (visible: boolean) => {
      const opacity = visible ? "1" : "0";
      cursor.style.opacity = opacity;
      follower.style.opacity = visible ? "0.45" : "0";
    };

    const moveCursor = (event: PointerEvent) => {
      const { clientX, clientY } = event;

      if (rafId) {
        window.cancelAnimationFrame(rafId);
      }

      rafId = window.requestAnimationFrame(() => {
        cursor.style.left = `${clientX}px`;
        cursor.style.top = `${clientY}px`;
        follower.style.left = `${clientX}px`;
        follower.style.top = `${clientY}px`;
        setOpacity(true);
      });
    };

    const addHoverState = () => {
      cursor.classList.add("cursor-hover");
      follower.classList.add("cursor-follower-hover");
    };

    const removeHoverState = () => {
      cursor.classList.remove("cursor-hover");
      follower.classList.remove("cursor-follower-hover");
    };

    const handlePointerOver = (event: PointerEvent) => {
      const target = event.target as HTMLElement | null;
      if (target?.closest("a, button, [role='button'], .cursor-interactive")) {
        addHoverState();
      }
    };

    const handlePointerOut = (event: PointerEvent) => {
      const target = event.target as HTMLElement | null;
      if (target?.closest("a, button, [role='button'], .cursor-interactive")) {
        removeHoverState();
      }
    };

    const handlePointerLeaveDocument = () => {
      setOpacity(false);
      removeHoverState();
    };

    const handlePointerEnter = () => setOpacity(true);

    window.addEventListener("pointermove", moveCursor, { passive: true });
    window.addEventListener("pointerenter", handlePointerEnter, { passive: true });
    window.addEventListener("pointerleave", handlePointerLeaveDocument, { passive: true });
    document.addEventListener("pointerover", handlePointerOver, { passive: true });
    document.addEventListener("pointerout", handlePointerOut, { passive: true });

    return () => {
      if (rafId) window.cancelAnimationFrame(rafId);
      rafId = null;
      window.removeEventListener("pointermove", moveCursor);
      window.removeEventListener("pointerenter", handlePointerEnter);
      window.removeEventListener("pointerleave", handlePointerLeaveDocument);
      document.removeEventListener("pointerover", handlePointerOver);
      document.removeEventListener("pointerout", handlePointerOut);
    };
  }, [shouldRender]);

  if (!shouldRender) return null;

  return (
    <>
      <div ref={cursorRef} className="custom-cursor hidden md:block opacity-0" />
      <div ref={followerRef} className="cursor-follower hidden md:block opacity-0" />
    </>
  );
};
