// src/pages/OrderSuccess.tsx
'use client';

import { Link, useSearchParams } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import { CheckCircle2, ArrowRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useTranslation } from 'react-i18next';

const OrderSuccess = () => {
  const { t } = useTranslation();
  const [searchParams] = useSearchParams();
  const orderId = searchParams.get('orderId');

  return (
    <>
      <Helmet>
        <title>{t('order.successPage.metaTitle', { defaultValue: 'Permintaan Diterima - ekalliptus' })}</title>
        <meta
          name="description"
          content={t('order.successPage.metaDescription', {
            defaultValue: 'Terima kasih! Tim ekalliptus sudah menerima permintaan servis perangkat Anda.',
          })}
        />
        <meta name="robots" content="noindex" />
      </Helmet>

      <section className="content-vis relative flex min-h-[70vh] items-center justify-center px-4 py-24">
        <div className="absolute inset-0 pointer-events-none">
          <div className="floating absolute inset-x-0 top-10 mx-auto h-72 w-72 rounded-full bg-primary/5 blur-3xl" />
          <div className="absolute bottom-0 right-10 h-40 w-40 rounded-full border border-primary/10 bg-secondary/10 blur-[90px]" />
        </div>

        <div className="glass-panel neon-border relative z-10 max-w-2xl rounded-3xl p-10 text-center shadow-elegant">
          <div className="mx-auto mb-6 flex h-20 w-20 items-center justify-center rounded-full bg-primary/15 text-primary">
            <CheckCircle2 className="h-10 w-10" strokeWidth={1.5} />
          </div>
          <h1 className="text-3xl font-semibold text-foreground md:text-4xl">
            {t('order.successPage.title', { defaultValue: 'Permintaan servis berhasil dikirim' })}
          </h1>
          <p className="mt-4 text-base text-muted-foreground">
            {t('order.successPage.description', {
              defaultValue:
                'Tim kami akan menghubungi Anda dalam 1x24 jam melalui kontak yang sudah dicantumkan. Mohon siapkan perangkat dan detail tambahan agar proses pengecekan lebih cepat.',
            })}
          </p>

          {orderId && (
            <div className="mt-6 rounded-2xl border border-border/50 bg-card/50 px-5 py-4 text-sm text-foreground/80">
              <span className="font-semibold">{t('order.successPage.orderId', { defaultValue: 'ID Permintaan' })}</span>
              <span className="ml-2 font-mono text-muted-foreground">{orderId}</span>
            </div>
          )}

          <div className="mt-8 flex flex-col gap-3 sm:flex-row sm:justify-center">
            <Button asChild size="lg" className="rounded-2xl px-6 py-5 text-base font-semibold">
              <Link to="/">
                {t('order.successPage.backHome', { defaultValue: 'Kembali ke beranda' })}
              </Link>
            </Button>
            <Button
              asChild
              variant="outline"
              size="lg"
              className="rounded-2xl border-primary/30 text-primary hover:bg-primary/10"
            >
              <Link to="/order" className="flex items-center gap-2">
                {t('order.successPage.newRequest', { defaultValue: 'Kirim permintaan lain' })}
                <ArrowRight className="h-4 w-4" />
              </Link>
            </Button>
          </div>
        </div>
      </section>
    </>
  );
};

export default OrderSuccess;

// pages/order-success.vue
<template>
  <div>
    <Head>
      <Title>{{ $t('orderSuccess.title', 'Pesanan Berhasil') }} - ekalliptus</Title>
    </Head>

    <div class="min-h-screen flex items-center justify-center py-12 px-4">
      <div class="max-w-md w-full text-center">
        <div class="glass-panel neon-border rounded-3xl p-8 md:p-12">
          <!-- Success Icon -->
          <div class="mx-auto mb-6 h-20 w-20 rounded-full bg-green-500/20 flex items-center justify-center">
            <CheckCircle class="h-10 w-10 text-green-500" />
          </div>

          <h1 class="text-2xl md:text-3xl font-bold text-foreground mb-4">
            {{ $t('orderSuccess.heading', 'Terima Kasih!') }}
          </h1>

          <p class="text-muted-foreground mb-8">
            {{ $t('orderSuccess.message', 'Permintaan Anda telah berhasil dikirim. Tim kami akan menghubungi Anda dalam 1x24 jam melalui WhatsApp atau Email.') }}
          </p>

          <div class="space-y-4">
            <NuxtLink
              to="/"
              class="block w-full rounded-xl bg-primary px-6 py-3 font-semibold text-primary-foreground transition hover:bg-primary/90 cursor-interactive"
            >
              {{ $t('orderSuccess.backHome', 'Kembali ke Beranda') }}
            </NuxtLink>

            <a
              href="https://wa.me/6281999900306"
              target="_blank"
              rel="noopener noreferrer"
              class="inline-flex items-center justify-center gap-2 w-full rounded-xl border border-border/30 bg-card/20 px-6 py-3 font-semibold text-foreground transition hover:bg-card/30 cursor-interactive"
            >
              <Phone class="h-5 w-5 text-green-500" />
              {{ $t('orderSuccess.contactWhatsApp', 'Hubungi via WhatsApp') }}
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { CheckCircle, Phone } from 'lucide-vue-next'
</script>
